chore[git-shared-checkout]: Added --remove

diff --git a/git-shared-checkout b/git-shared-checkout
--- a/git-shared-checkout
+++ b/git-shared-checkout
@@ -9,7 +9,7 @@
 #
 # It needs to be possible to run without any other libraries (e.g. in a fresh docker image) and it should not produce any output on stdout except the path to the checkout (and error messages on stderr if needed).
 #
-GIT_SHARED_CHECKOUT_VERSION="0.0.5"
+GIT_SHARED_CHECKOUT_VERSION="0.0.5a"
 [[ -z "${HOME:-}" ]] && SHARED_GIT_DIR="/usr/share/gits-shared"
 [[ -n "${HOME:-}" ]] && SHARED_GIT_DIR="${HOME}/gits-shared"
 
@@ -59,33 +59,39 @@ function main()
     fi
 
     local repo_path="${1:-}"
-    local ref="${2:-}"
-
     local ref_type=''
     local ref_value=''
-    if [[ "$ref" == --hash=* ]]; then
+    if [[ "${2:-}" == --ref=#* ]]; then
+        ref="${ref#--ref=#}"
+
         ref_type='hash'
-        ref_value="${ref#--hash=}"
-    elif [[ "$ref" == --hash=* ]]; then
-        ref_type='hash-only'
-        ref_value="${ref#--hash=}"
-    elif [[ "$ref" == '--ref=#'* ]]; then
-        ref_type='hash'
-        ref_value="${ref#--ref=#}"
+        ref_value="${ref#\#}"
         echo "⚠️  Deprecated used of --ref=#${ref_value} :  Use --ref=hash:${ref_value} instead" >&2
-    elif [[ "$ref" == '--ref=branch:'* ]]; then
+    elif [[ "${2:-}" == --ref=* ]]; then
+        ref="${2#--ref=}"
+
+        if [[ -n "$ref" ]]; then
+            for x in hash hash-only branch tag ; do
+                if [[ "$ref" == "$x:"* ]]; then
+                    ref_type="$x"
+                    ref_value="${ref#"$x:"}"
+                    break
+                fi
+            done
+
+            if [[ -z "$ref_type" ]]; then
+                echo "⚠️  Invalid format for --ref=${ref} : Expected --ref=branch:<branch_name> or --ref=tag:<tag_name> or --ref=hash:<hash_value> or --ref=hash-only:<hash_value>" >&2
+                repo_path='' # Force show help and exit with error
+            fi
+        fi
+    elif [[ "${2:-}" == 'branch:'* ]]; then
         ref_type='branch'
-        ref_value="${ref#--ref=branch:}"
-    elif [[ "$ref" == '--ref=tag:'* ]]; then
-        ref_type='tag'
-        ref_value="${ref#--ref=tag:}"
-    elif [[ "$ref" == --ref=* ]]; then
-        echo "⚠️  Invalid use of ${ref} : Expected --ref=branch:xxx, --ref=tag:xxx , --ref=hash:xxx, --ref=hash-only:xxx" >&2
-        repo_path='' # Force show help and exit with error
-    elif [[ -n "$ref" ]]; then
-        echo "⚠️  Deprecated used of ${ref} :  Use --ref=branch:${ref} instead" >&2
+        ref_value="${2#branch:}"
+        echo "⚠️  Deprecated used of ${2} :  Use --ref=$2 instead" >&2
+    elif [[ -n "${2:-}" ]]; then
+        echo "⚠️  Deprecated used of ${2} :  Use --ref=branch:${2} instead" >&2
         ref_type='branch'
-        ref_value="$ref"
+        ref_value="${2}"
     fi
 
     if [[ -z "$repo_path" ]] || [[ "$repo_path" == '--'* ]]; then
@@ -238,6 +244,8 @@ EXE_NAME="$(basename "$THIS_EXE")"
 
 if [[ "${1:-}" == '--install' ]]; then
     do_install_directly
+elif [[ "${1:-}" == "--remove" ]] || [[ "${1:-}" == "--uninstall" ]]; then
+    (sleep 0.5 && echo "Removing $THIS_EXE" && rm -f "$THIS_EXE" && echo "Removed $THIS_EXE") &
 else
     main "$@"
 fi
